# Optimized SLAM Toolbox Configuration for UGV Beast
# Tuned for BETTER MAPPING ACCURACY
# Key changes:
# - More frequent scan processing for detailed maps
# - Tighter scan matching for accuracy
# - Better loop closure detection
# - Higher resolution for indoor environments

slam_toolbox:
  ros__parameters:
    # Solver settings (Ceres optimizer)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frame configuration
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    # Operating mode
    mode: mapping

    # ===========================================
    # SCAN PROCESSING - More frequent for detail
    # ===========================================
    throttle_scans: 1              # Process every scan
    minimum_time_interval: 0.2     # REDUCED: Process scans more often (was 0.5)
    transform_publish_period: 0.02 # 50Hz TF publish rate

    # ===========================================
    # MAP SETTINGS - Higher resolution
    # ===========================================
    map_update_interval: 2.0       # REDUCED: Update map more often (was 5.0)
    resolution: 0.03               # INCREASED: 3cm resolution (was 5cm) - more detail

    # ===========================================
    # LASER RANGE - Tuned for LD19
    # ===========================================
    min_laser_range: 0.15          # Ignore readings < 15cm (robot body interference)
    max_laser_range: 8.0           # REDUCED: LD19 is more accurate at closer range

    # Transform settings
    transform_timeout: 0.5
    tf_buffer_duration: 30.0

    # Memory allocation
    stack_size_to_use: 40000000

    # ===========================================
    # SCAN MATCHING - Tighter for accuracy
    # ===========================================
    use_scan_matching: true
    use_scan_barycenter: true

    # Motion thresholds - capture more poses for better map
    minimum_travel_distance: 0.1   # REDUCED: Add scan every 10cm (was 0.3)
    minimum_travel_heading: 0.15   # REDUCED: Add scan every ~8.5 degrees (was 0.3)

    # Scan buffer - more scans for matching
    scan_buffer_size: 15           # INCREASED from 10
    scan_buffer_maximum_scan_distance: 8.0

    # Scan matching parameters - tighter matching
    link_match_minimum_response_fine: 0.15  # INCREASED: require better matches (was 0.1)
    link_scan_maximum_distance: 1.0         # REDUCED: tighter matching distance (was 1.5)

    # ===========================================
    # LOOP CLOSURE - Critical for accuracy
    # ===========================================
    do_loop_closing: true
    loop_match_minimum_chain_size: 5        # REDUCED: detect loops earlier (was 10)
    loop_match_maximum_variance_coarse: 2.0 # REDUCED: stricter variance (was 3.0)
    loop_match_minimum_response_coarse: 0.4 # INCREASED: require better coarse match
    loop_match_minimum_response_fine: 0.5   # INCREASED: require better fine match

    # Additional settings
    enable_interactive_mode: false
    use_map_saver: true

    # ===========================================
    # CORRELATION SEARCH - Tighter search space
    # ===========================================
    correlation_search_space_dimension: 0.3      # REDUCED (was 0.5)
    correlation_search_space_resolution: 0.008   # FINER (was 0.01)
    correlation_search_space_smear_deviation: 0.05  # REDUCED (was 0.1)

    # Loop search - balance between finding loops and false positives
    loop_search_space_dimension: 6.0             # REDUCED (was 8.0)
    loop_search_space_resolution: 0.03           # FINER (was 0.05)
    loop_search_space_smear_deviation: 0.02      # REDUCED (was 0.03)

    # Fine search parameters
    distance_variance_penalty: 0.3    # REDUCED: less penalty for distance
    angle_variance_penalty: 0.8       # REDUCED: less penalty for angle
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.262  # REDUCED: ~15 degrees (was 20)
    coarse_angle_resolution: 0.0262    # FINER: ~1.5 degrees (was 2)

    # Map quality thresholds
    minimum_score: 0.0
    minimum_angle_penalty: 0.85       # Slightly reduced
    minimum_distance_penalty: 0.4     # Slightly reduced
    use_response_expansion: true
