# Optimized SLAM Toolbox Configuration for UGV Beast
# Based on analysis of ugv_ws defaults with improvements for better mapping

slam_toolbox:
  ros__parameters:
    # Solver settings (Ceres optimizer)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frame configuration
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    # Operating mode
    mode: mapping  # 'mapping' or 'localization'

    # Scan processing
    throttle_scans: 1              # Process every scan
    minimum_time_interval: 0.5     # Min time between processed scans
    transform_publish_period: 0.02 # 50Hz TF publish rate

    # Map settings
    map_update_interval: 5.0       # How often to update the map (seconds)
    resolution: 0.05               # 5cm resolution (matches costmaps)

    # Laser range settings
    min_laser_range: 0.2           # Ignore readings < 20cm (robot body)
    max_laser_range: 12.0          # LD19 effective range ~12m

    # Transform settings
    transform_timeout: 1.0         # Increased for EKF latency
    tf_buffer_duration: 60.0       # TF buffer size - increased for startup

    # Memory allocation
    stack_size_to_use: 40000000    # 40MB stack

    # Scan matching
    use_scan_matching: true
    use_scan_barycenter: true

    # Motion thresholds for new scan processing
    minimum_travel_distance: 0.3   # Reduced from 0.5 for more frequent updates
    minimum_travel_heading: 0.3    # Reduced from 0.5 for more frequent updates

    # IMPROVED: Scan buffer settings
    scan_buffer_size: 10           # INCREASED from 3 (default: 10)
    scan_buffer_maximum_scan_distance: 10.0

    # Scan matching parameters
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5

    # IMPROVED: Loop closure settings
    do_loop_closing: true
    loop_match_minimum_chain_size: 10   # INCREASED from 3 (default: 10)
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Additional recommended settings
    enable_interactive_mode: false  # Disable for autonomous operation
    use_map_saver: true             # Enable map saving capability

    # Correlation settings for better matching
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop search settings
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Fine search parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349  # ~0.2 degrees
    coarse_search_angle_offset: 0.349   # ~20 degrees
    coarse_angle_resolution: 0.0349     # ~2 degrees

    # Map thresholds
    minimum_score: 0.0
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
